Discord event syncing
ItemizeNTNU/website pull request #45
Opened 2022-02-24 12:15 UTC by calidbaba

- Events made on the website is also created as an discord event on the discord server
- Updating and deleting is also synced
- Most of the logic is in src/server/utils.js, maybe it should be in the src/server/discord.js. However that seemed to be more logic connected with discord login.

2022-02-24 13:38 UTC, kristianvld requested changes

2022-02-24 13:38 UTC, kristianvld commented on src/routes/arrangementer.svelte
> +	const skjulArrangemant = () => {
Please keep it to english in the chat folks 🙃

2022-02-24 13:38 UTC, kristianvld commented on src/routes/arrangementer.svelte
> +	const delArrangemangtDiscord = () => {
English please

2022-02-24 13:38 UTC, kristianvld commented on src/routes/arrangementer.svelte
> +				<label><span class="col">Skjult:</span> <input type="checkbox" bind:value={newEvent.hidden} bind:checked={newEvent.hidden} on:change={skjulArrangemant} /></label>
The "value" attributes of checkboxes has no function or effect. Use `checked` only.

2022-02-24 13:38 UTC, kristianvld commented on src/server/utils.js
> +export const deleteDiscordEvent = async (eventId) => {
Please move this to discord.js

2022-02-24 13:38 UTC, kristianvld commented on src/server/utils.js
> +	return await fetchResource(`https://discord.com/api/v8/guilds/${process.env.DISCORD_SERVER_ID}/scheduled-events/${eventId}`, {
Please use the discordFetch function, no need for duplicate code doing the same thing.

2022-02-24 13:38 UTC, kristianvld commented on src/server/utils.js
> +export const makeDiscordEvent = async (jsonData, isUpdate) => {
Please move this to discord.js

2022-02-24 21:36 UTC, calidbaba commented on src/routes/arrangementer.svelte
> +	const delArrangemangtDiscord = () => {
shieet

2022-03-08 15:05 UTC, kristianvld approved these changes

2022-03-08 15:07 UTC, merged